# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateTimeField(null=True)),
                ('assignee', models.ForeignKey(help_text='Designates who assigned a task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to_do', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Designates who will review a task. If no reviewer is set, assignee takes full responsibility for a task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
